ehealth4everyone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('medhistory/', include('usersmedhistory.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

user/urls.py
from django.urls import path
from user.views import heathworkers, index, patients


app_name = 'user'

urlpatterns = [
    # For the home page
    path('', index.dashboard, name='dashboard'),

    # for health worker registration
    path('healthworker/', heathworkers.healthworker_profile_view, name='healthworker'),

    # for patient registration
    path('patient/', patients.patient_profile_view, name='patient'),

]

usersmedhistory/urls.py
from django.urls import path
from .views import create_medical_record, medial_history, statistics, chart_view, condition_status_view

app_name = 'usersmedhistory'


urlpatterns = [
    # this renders the create_medical_record view which is a form for users to fill
    path('', create_medical_record, name='medform'),

    # this renders the list of all our users details but is accessible to only health workers
    path('medlist/', medial_history, name='medlist'),

    # this renders a fields that show statical data of how each fields relate and a filter functionality
    path('userstats/', statistics, name='stats'),

    # this points to the view that renders our genotype chart
    path('chart/', chart_view, name='chart_data'),

    # this points to the view that renders our contagious and non_contagious chart
    path('condition/', condition_status_view, name='condition_data'),
]

templates/medicalrecord/illstatistics.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}
<div class="container mx-auto mt-5 pt-5">

    <div class="mb-4">
        <h3 class="text-center font-weight-bold">LET THE DATA TELL THE STORY</h3>
        <hr>
        <h5 class=" mb-1 "></h5>
        <p class="text-danger font-weight-bold text-justified">The sole purpose of us and our partners making this data
            available is for <mark>Research</mark>, <mark>Educational</mark> and <mark>Awareness</mark>purposes.
            Names of our users have intentionally been removed to safeguard their identity.
        </p>
        <p class="text-center text-danger">You are advised to desist from using this data outside
            the scope of what its intended for, if found you will be persecuted</p>
    </div>
    <div class="row mb-5">
        <!-- This div renders the different charts on our page -->
        <div id="container" class="col-md-6 col-sm-12" data-url="{% url 'usersmedhistory:chart_data' %}"></div>
        <div id="status" class="col-md-6 col-sm-12" data-url="{% url 'usersmedhistory:condition_data' %}"></div>
        <!-- end of the chart div -->

    </div>
    <div class="row">
        <!-- This renders the table containing details of users who submitted the medform -->
        <div class="col-md-9 col-sm-12 table-responsive">
            <table style="width:100%" class="table table-striped table-bordered ">
                <tr class="text-uppercase">
                    <th>ID</th>
                    <th>AGE</th>
                    <th>GENOTYPE</th>
                    <th>HEALTH </th>
                    <th>EFFECT</th>
                    <th>CONDITION</th>
                    <th>MARRIED</th>
                    <th>COUNTRY</th>
                    <th>STATE</th>

                </tr>
                {% for record in queryset %}
                <tr>
                    <td>{{ record.id }}</td>
                    <td>{{ record.age }}</td>
                    <td>{{ record.genotype }}</td>
                    <td>{{ record.health_challenge }}</td>
                    <td>{{ record.health_status }}</td>
                    <td>{{ record.health_condition }}</td>
                    <td>{{ record.married }}</td>
                    <td>{{ record.country }}</td>
                    <td>{{ record.state }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <!-- End of list of users who submoitted the medform -->

        <!-- This renders the filtering options -->
        <div class="col-md-3 col-sm-12">
            <form method="GET" class="mb-5 shadow font-weight-bold h5 text-uppercase">
                <div class="row">
                    <!--For filtering out genotypes-->
                    <div class="form-group my-3 col-md-12">
                        <div class="col-12 text-center">
                            <label for="genotype">Genotype</label></div>
                        <div class="col-12 text-center">
                            <select id="genotype" name="genotype" class="w-75 mx-auto">
                                <option name=""></option>
                                <option name="AA">AA</option>
                                <option name="AS">AS</option>
                                <option name="SS">SS</option>
                            </select>
                            <hr>
                        </div>
                    </div>

                    <!--For filtering users based on stat-->
                    <div class="form-group col-md-12">
                        <div class="col-12 text-center">
                            <label for="state">State</label>
                        </div>
                        <div class="col-12 text-center">
                            <select id="state" name="state" class="w-75 mx-auto">
                                <option name=""></option>
                                <option name="Imo">Imo</option>
                                <option name="Anambra">Anambra</option>
                                <option name="Unata">Abuja</option>
                                <option name="Unata">Rivers</option>
                                <option name="Unata">Lagos</option>
                                <option name="Unata">Kastina</option>
                                <option name="Unata">Kano</option>
                                <option name="Unata">Delta</option>
                                <option name="Unata">Enugu</option>
                                <option name="Unata">Abia</option>
                                <option name="Unata">Bayelsa</option>
                            </select>
                        </div>
                        <hr>
                    </div>

                    <!--For filtering users based on country-->
                    <div class="form-group col-md-12">
                        <div class="col-12 text-center">
                            <label for="country">Country</label>
                        </div>
                        <div class="col-12 text-center">
                            <select id="country" name="country" class="w-75 mx-auto">
                                <option name=""></option>
                                <option name="Nigeri">Nigeria</option>
                            </select>
                        </div>
                        <hr>
                    </div>

                    <!--For filtering users based on their health challenges-->
                    <div class="form-group my-3 col-md-12">
                        <div class="col-12 text-center">
                            <label for="health">Health</label></div>
                        <div class="col-12 text-center">
                            <select id="health" name="health" class="w-75 mx-auto">
                                <option name=""></option>
                                <option name="Cancer">Cancer</option>
                                <option name="HIV">HIV</option>
                                <option name="Ebola">Ebola</option>
                                <option name="Low BP">Low BP</option>
                                <option name="High BP">High BP</option>
                                <option name="Diabetic">Diabetics</option>
                                <option name="Liver Failure">Liver Failure</option>
                                <option name="Chicken Box">Chicken Box</option>
                            </select>
                            <hr>
                        </div>
                    </div>
                    <div class="form-group my-3 col-12">
                        <div class="col-12 text-center">
                            <button class="btn btn-success w-75 btn-center" type="submit">Filter</button>
                        </div>
                    </div>

                </div>
            </form>
        </div>
        <!-- End of filtering form options -->
    </div>

    {% include "includes/pagination.html" %}
</div>


{% endblock content %}

templates/medicalrecord/medicalform.html
{% extends "index.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Medical Record{% endblock %}

{% block content %}
<div class="container mt-5 pt-5 mb-5 pt-5 text-center">
    <h4 class="text-uppercase mb-3 font-weight-bold">Please fill in your details here</h4>
    <p class="text-success font-weight-bold text-justified">This form helps us keep a data of the medical histories of
        users in a particular
        geographical zone,
        which can help attract government support, NGO's and International organization to support and finance projects
        in this areas.
    </p>
    <hr>
    <form method="post" class="shadow col-md-6 col-sm-12 mx-auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="my-4 ">Save changes</button>
    </form>
</div>
{% endblock %}

templates/medicalrecord/medicalhistory.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}

<div class="container text-center mt-5 pt-5">
    <h3 class="text-uppercase font-weight-bold mb-3">List of all registered patients who have gracious submitted their
        complete medical details
    </h3>
    <h5 class="text-danger text-center">Accessible to only Health workers and DataHealth Admin</h5>
    <hr>
    <div class="table-responsive">
        <table style="width:100%" class="table table-striped table-bordered ">
            <tr class="text-uppercase">
                <th>ID</th>
                <th>Name</th>
                <th>Age</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Health Challenge</th>
                <th>EFFECT</th>
                <th>CONDITION</th>
                <th>Country</th>
                <th>State</th>
                <th>Genotype</th>
                <th>Married</th>
            </tr>
            {% for record in records %}
            <tr>
                <td>{{record.id}}</td>
                <td class="text-capitalize">{{ record.user }}</td>
                <td>{{ record.age }}</td>
                <td>{{ record.email }}</td>
                <td>{{ record.phone }}</td>
                <td>{{ record.health_challenge }}</td>
                <td>{{ record.health_status }}</td>
                <td>{{ record.health_condition }}</td>
                <td>{{ record.country }}</td>
                <td>{{ record.state }}</td>
                <td>{{ record.genotype }}</td>
                <td>{{ record.married }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

templates/medicalrecord/permission_denied.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}

<div class="container text-center my-5 py-5">
    <h1 class="display-1 mt-5 mb-2 font-weight-bold mx-auto">Sorry!!!</h1>
    <hr>
    <h5 class="text-uppercase font-weight-bold">You do not have permission to view this page.</h5>

</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/medicalrecord/success.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}

<div class="container text-center my-5 py-5">
    <h1 class="mt-5 mb-2 font-weight-bold mx-auto">Your form has been successfully submitted.</h1>
    <h5 class="text-uppercase font-weight-bold">Thank you for trusting us</h5>
    <p>Back to <a href="/">Home</a></p>
</div>
{% endblock %}

{% block footer %}

{% endblock %}