ehealth4everyone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('medhistory/', include('usersmedhistory.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

user/urls.py
from django.urls import path
from user.views import heathworkers, index, patients


app_name = 'user'

urlpatterns = [
    # For the home page
    path('', index.dashboard, name='dashboard'),

    # for health worker registration
    path('healthworker/', heathworkers.healthworker_profile_view, name='healthworker'),

    # for patient registration
    path('patient/', patients.patient_profile_view, name='patient'),

]

templates/includes/Aboutus.html
<div class="row">
    <div class="shadow mt-5 text-left col-md-6">
        <ol class="py-3">
            <h5 class="text-uppercase text-center">our mission</h5>
            <hr>
            <p>Our mission is to make data readily available for</p>
            <hr>
            <li>Educational and Research purposes</li>
            <li>Medical support from NGO's, Government, International Organizations for our registered users</li>
            <li>Collaboration between Health Workers and Patients</li>
            <li>Real time monitoring and combating of epidemic outbreaks</li>
        </ol>
    </div>

    <div class="shadow mt-5 text-left col-md-6">

        <h5 class="text-uppercase pt-3 text-center">Who are we</h5>
        <hr>
        <p>We are a dedicated team from all over Nigeria with the shared vision of changing the narrative of
            the health system in Nigeria</p>
        <p>We are focused on decentralizing the health system in Nigeria and provide Nigerian people
            with real access to NGO's, International Organization, Foreign Aids that they need to combat
            various diseases and have access to people ready to help them
        </p>
    </div>
</div>

templates/includes/homepagebackground.html
{% load crispy_forms_tags %}
{% load staticfiles %}

<!-- header background -->
<header id="header">
    <div class="container mt-5 pt-5">
        <div class="banner text-center text-light mt-5 pt-5">
            {% if request.user.is_authenticated %}
            <h1 class="text-white"><strong>DATA HEALTH FOR AFRICAN</strong></h1>
            <h4 class="pb-3">Changing the narrative of the Health of African People</h4>
            {% include 'includes/Aboutus.html' %}
            {% else %}
            <h1><strong class="text-white">HEALTH DATA COLLECTION CENTER</strong></h1>
            <h4 class="pb-3">Changing the narrative of the Health of African People</h4>
            <h5>Register as</h5>
            <div class="btn btn-success mr-5 mb-3 ">
                <a href="{% url 'user:healthworker' %}" class="p-5 text-white"> Health Worker</a>
            </div>
            <div class="btn btn-success">
                <a href="{% url 'user:patient' %}" class="p-5 text-white">Patient</a>
            </div>
            {% include 'includes/Aboutus.html' %}
            {% endif %}
        </div>
    </div>
</header>

templates/includes/pagination.html
<div class="pagination spacing pb">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>