ehealth4everyone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('medhistory/', include('usersmedhistory.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

user/urls.py
from django.urls import path
from user.views import heathworkers, index, patients


app_name = 'user'

urlpatterns = [
    # For the home page
    path('', index.dashboard, name='dashboard'),

    # for health worker registration
    path('healthworker/', heathworkers.healthworker_profile_view, name='healthworker'),

    # for patient registration
    path('patient/', patients.patient_profile_view, name='patient'),

]

usersmedhistory/urls.py
from django.urls import path
from .views import create_medical_record, medial_history, statistics, chart_view, condition_status_view

app_name = 'usersmedhistory'


urlpatterns = [
    # this renders the create_medical_record view which is a form for users to fill
    path('', create_medical_record, name='medform'),

    # this renders the list of all our users details but is accessible to only health workers
    path('medlist/', medial_history, name='medlist'),

    # this renders a fields that show statical data of how each fields relate and a filter functionality
    path('userstats/', statistics, name='stats'),

    # this points to the view that renders our genotype chart
    path('chart/', chart_view, name='chart_data'),

    # this points to the view that renders our contagious and non_contagious chart
    path('condition/', condition_status_view, name='condition_data'),
]

templates/charts.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
{% endblock %}


{% block scripts %}
<div id="container" data-url="{% url 'usersmedhistory:chart_data' %}"></div>
{% include "includes/defaultjsfiles.html" %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/highcharts.src.js' %}"></script>
<script>
    $.ajax({
        url: $("#container").attr("data-url"),
        dataType: 'json',
        success: function (data) {
            Highcharts.chart("container", data);
        }
    });
</script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    {% load crispy_forms_tags %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %} DataHealth{% endblock %}</title>
    <!-- core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
</head>

<body>

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/"><strong class="primary-color">DataHealth</strong> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto text-light">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usersmedhistory:stats' %}">MedStatistics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usersmedhistory:medlist' %}">MedStore</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usersmedhistory:medform' %}">MedForm</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <span class="navbar-text text-uppercase">
                        <b> {{ user.get_username }}</b>
                    </span>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                    </li>
                    {% else %}
                    <ul class="navbar-nav ">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a>
                        </li>
                    </ul>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}


    {% block content %}
    <!-- this brings in the content of homepagebackground whenever the homepage is loaded -->
    {% include "includes/homepagebackground.html" %}
    <!-- end of homepagebackground -->

    {% endblock %}
    {% block scripts %}

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/highcharts.src.js' %}"></script>

    <!-- this scripts are used to create the different charts in our web pages -->
    <!-- this renders the genotype chart -->
    <script>
        $.ajax({
            url: $("#container").attr("data-url"),
            dataType: 'json',
            success: function (data) {
                Highcharts.chart("container", data);
            }
        });
    </script>
    <!-- this renders the contagious and non contagious chart -->
    <script>
        $.ajax({
            url: $("#status").attr("data-url"),
            dataType: 'json',
            success: function (data) {
                Highcharts.chart("status", data);
            }
        });
    </script>
    {% endblock %}

    {% block footer %}
    <footer class="bg-dark text-center py-4 text-white">
        This Platform was developed with love by Baron
    </footer>
    {% endblock %}
</body>

</html>